guest_log_in_button = "//button[text()='Guest log in']"
sign_in_button = "//button[text()='Sign In']"
about_button = "//button[@appscrollto='aboutSection']"
contacts_button = "//button[@appscrollto='contactsSection']"
guest_log_in_button_2 = "//button[@class='header-link -guest']"
do_more_title = "//h1[@class='hero-descriptor_title display-2']"
sign_up_button = "//button[@class='hero-descriptor_btn btn btn-primary' and text()='Sign up']"
video_frame = "//video[@class='video-stream html5-main-video']"
icon_facebook = "//span[@class='socials_icon icon icon-facebook']"
icon_telegram = "//span[@class='socials_icon icon icon-telegram']"
icon_youtube = "//span[@class='socials_icon icon icon-youtube']"
icon_instagram = "//span[@class='socials_icon icon icon-instagram']"
icon_linkedin = "//span[@class='socials_icon icon icon-linkedin']"
it_hillel_link = "//a[@class='contacts_link display-4' and text()='ithillel.ua']"
support_contacts_link = "//a[@class='contacts_link h4']"
garage_button = "//a[@class='btn header-link -active' and text()='Garage']"
fuel_expenses_button = "//a[@class='btn header-link' and text()='Fuel expenses']"
instructions_button = "//a[@class='btn header-link' and text()='Instructions']"
garage_side_bar_button = "//a[@routerlink='garage']"
expenses_side_bar_button = "//a[@routerlink='expenses']"
instructions_side_bar_button = "//a[@routerlink='instructions']"
side_bar_log_out_button = "//a[@class='btn btn-link text-danger btn-sidebar sidebar_btn']"
add_car_button = "//button[text()='Add car']"
add_expense_button = "//button[text()='Add an expense']"
search_button = "//button[@class='instructions-search-controls_search btn btn-primary']"
